BongbongWeb/Models/ErrorViewModel.cs
namespace BongbongWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BongbongWeb/Controllers/HomeController.cs
using Bulky.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BongbongWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BongbongWeb/Controllers/ReservationStatusController.cs
using BongbongWeb.Data;
using Bulky.DataAccess.Repository;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Microsoft.AspNetCore.Mvc;

namespace BongbongWeb.Controllers
{
    public class ReservationStatusController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;                      //필드선언
        public ReservationStatusController(IUnitOfWork unitOfWork)     //생성자
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<ReservationStatus> reservations = _unitOfWork.ReservationStatus.GetAll().ToList();
            // List<REservationStatus> 대신 var로 사용가능
            return View(reservations);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ReservationStatus obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.ReservationStatus.Add(obj);
                _unitOfWork.Save();
                TempData["Success"] = "생성 성공";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            ReservationStatus? FromDb = _unitOfWork.ReservationStatus.Get(u => u.Id == id);
            if (FromDb == null)
            {
                return NotFound();
            }
            return View(FromDb);
        }
        [HttpPost]
        public IActionResult Edit(ReservationStatus obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.ReservationStatus.Update(obj);
                _unitOfWork.Save();
                TempData["Success"] = "생성 성공";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            ReservationStatus? FromDb = _unitOfWork.ReservationStatus.Get(u => u.Id == id);
            if (FromDb == null)
            {
                return NotFound();
            }
            return View(FromDb);

        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            ReservationStatus? obj = _unitOfWork.ReservationStatus.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.ReservationStatus.Remove(obj);
            _unitOfWork.Save();
            TempData["Success"] = "생성 성공";
            return RedirectToAction("Index");

        }
    }
}

BongbongWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BongbongWeb/Views/ReservationStatus/Create.cshtml
@model ReservationStatus        


<form method="post">
  

    <div class="border p-3 mt-4">
       <div>
           <h2 class="text-dark">예약 추가하기</h2>
           <hr/>
       </div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0">이름</label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label class="p-0" asp-for="PhoneNumber">전화번호</label>
            <input asp-for="PhoneNumber" class="form-control">
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="ReservationTime" class="p-0">예약 시간</label>
            <input asp-for="ReservationTime" class="form-control">
            <span asp-validation-for="ReservationTime" class="text-danger"></span>
        </div>
        
        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-dark form-control">추가하기</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="ReservationStatus" asp-action="Index" class="btn btn-ouline-secondary border form-control">
                    이전 화면으로
                </a>
            </div>
        </div>
    </div>

</form>

@section scripts
{
    @{
        <Partial name="_ValidationScriptsPartial" />
    }
}

BongbongWeb/Views/ReservationStatus/Delete.cshtml
@model ReservationStatus

<form method="post">
    <div class="border p-3 mt-4">
        <div>
            <h2 class="text-dark">예약 삭제</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0">이름</label>
            <input asp-for="Name" class="form-control">
        </div>
        <div class="mb-3 row p-1">
            <label class="p-0" asp-for="PhoneNumber">전화번호</label>
            <input asp-for="PhoneNumber" class="form-control">
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="ReservationTime" class="p-0">예약 시간</label>
            <input asp-for="ReservationTime" class="form-control">
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-dark form-control">삭제하기</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="ReservationStatus" asp-action="Index" class="btn btn-ouline-secondary border form-control">
                    이전 화면으로
                </a>
            </div>
        </div>
    </div>

</form>

BongbongWeb/Views/ReservationStatus/Edit.cshtml
@model ReservationStatus

<form method="post">
    <div class="border p-3 mt-4">
        <div>
            <h2 class="text-dark">예약 수정</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0">이름</label>
            <input asp-for="Name" class="form-control">
        </div>
        <div class="mb-3 row p-1">
            <label class="p-0" asp-for="PhoneNumber">전화번호</label>
            <input asp-for="PhoneNumber" class="form-control">
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="ReservationTime" class="p-0">예약 시간</label>
            <input asp-for="ReservationTime" class="form-control">
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-dark form-control">수정하기</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="ReservationStatus" asp-action="Index" class="btn btn-ouline-secondary border form-control">
                    이전 화면으로
                </a>
            </div>
        </div>
    </div>

</form>

@section scripts
    {
    @{
        <Partial name="_ValidationScriptsPartial" />
    }
}

BongbongWeb/Views/ReservationStatus/Index.cshtml
@model List<ReservationStatus>;

    <div class="container">
        <div class="row pt-4 pb-3">
            <div class="col-6">
                <h2>예약 리스트</h2>
             </div>
            <div class="col-6 text-end">
                <a asp-controller="ReservationStatus" asp-action="Create" class="btn btn-dark">
                <i class="bi bi-plus-square"></i> 예약 추가
                </a>
            </div>
        </div>
    </div>



<table class="table table-bordered table-striped">
    <thead>
        <tr>
           <th class="col-2">
               이름
           </th>
            <th class="col-2">
               전화번호
           </th>
            <th class="col-2">
               예약시간
           </th>
           <th class="col-6"></th>
           
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model.OrderBy(u=> u.Id))
        {
            <tr>
                <td>@obj.Name</td>    
                <td>@obj.PhoneNumber</td>    
                <td>@obj.ReservationTime</td>
                <td>
                    <div class="w-75 btn btn-group" role="group">
                        <a asp-controller="ReservationStatus" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-dark mx-2">
                            수정
                        </a>
                        <a asp-controller="ReservationStatus" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                            삭제
                        </a>
                    </div>
                </td>
            </tr>
        }        
        
    </tbody>
</table>

BongbongWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BongbongWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BongbongWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BongbongWeb<i class="bi bi-cloud-drizzle-fill"></i></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ReservationStatus" asp-action="Index">예약현황</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            BongbongWeb <i class="bi bi-cloud-drizzle-fill"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BongbongWeb/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');  //toastr.info에서 info소문자로
    </script>
    
}
@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.Error('@TempData["Error"]');
    </script>
    
}